# params.yaml

data_ingestion:
  data_url: C:\ESG\data\raw\company_esg_financial_dataset.csv 
  s3_bucket: "my-esg-bucket"                 
  aws_access_key: "YOUR_AWS_ACCESS_KEY"      
  aws_secret_key: "YOUR_AWS_SECRET_KEY"      
  s3_file_key: "datasets/processed_esg_dataset.csv"  
  region_name: "ap-south-1"   
        
  test_size: 0.25
  random_state: 42
  drop_columns: ["Unnamed: 0"]   # columns to drop during ingestion
  handle_missing: drop           # drop | mean | median | mode


data_preprocessing:
  output_dir: C:\ESG\data\interim
  output_file_name: processed_esg_dataset.csv


feature_engineering:
  enabled: true
  input_path:  C:\ESG\data\interim\processed_esg_dataset.csv 
  output_dir:  src/features
  output_file_name: featured_esg_dataset.csv

  # toggles
  financial_ratios: true
  esg_pillars: true
  temporal: true
  lag_features: true
  rolling_stats: true
  rolling_window: 3

  # hook for user functions (list any custom func names here)
  custom_funcs: []               

modeling:
  baseline_model: LinearRegression
  advanced_models: ["RandomForest", "XGBoost", "LightGBM", "CatBoost"]
  scoring_metric: r2
  cv_folds: 5
  random_state: 42

mlflow:
  tracking_uri: https://dagshub.com/virajdeshmukh080818/ESG.mlflow
  experiment_name: ESG_Advanced_Models
  dagshub_repo_owner: virajdeshmukh080818
  dagshub_repo_name: ESG

storage:
  raw_data_dir: data/raw
  processed_data_dir: data/interim
  models_dir: models
